import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next-pizza",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex gap-4 w-full h-16 bg-slate-300 text-black">
          <Link href="/" className="cursor-pointer">
            Home
          </Link>
          <Link href="/login" className="cursor-pointer">
            Login
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
